.TH CONNMAN-UI-GTK "1" "August 2013"
.SH NAME
connman-ui-gtk \- GTK tray icon for ConnMan
.SH DESCRIPTION
.PP
A full-featured GTK based trayicon UI for ConnMan.
.PP
It targets all WM/DM users but Gnome3 ones*. It works on any Linux WM/DM 
which provides a freedesktop compliant system tray. (kde, awesome, ...)
.PP
It exposes almost all features provided by ConnMan API (small features are 
missing, see TODO for more information). You can enable/disable a technology 
(wired, wifi, cellular, bt, ...), connect/disconnect a service, configure a 
service (IPv4, IPv6, DNS, Timeservers, etc...), share your current connection 
(tethering) and so on. Everything is accessible through the mouse via the 
trayicon, all with left and right click.
.PP
This program takes no arguments.
.SH AUTHOR
Written by Tomasz Bursztyka.
